//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestasAsignadas
    {
        public EncuestasAsignadas()
        {
            this.RtasXEncuestaAsignada = new HashSet<RtasXEncuestaAsignada>();
        }
    
        public int idEncuestaAsignada { get; set; }
        public Nullable<int> idEncuesta { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
        public Nullable<System.DateTime> fechaRespuesta { get; set; }
    
        public virtual Encuestas Encuestas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        public virtual ICollection<RtasXEncuestaAsignada> RtasXEncuestaAsignada { get; set; }
    }
}
