//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preguntas
    {
        public Preguntas()
        {
            this.RtasXEncuestaAsignada = new HashSet<RtasXEncuestaAsignada>();
        }
    
        public int idPregunta { get; set; }
        public string textoPregunta { get; set; }
        public Nullable<int> idEncuesta { get; set; }
    
        public virtual Encuestas Encuestas { get; set; }
        public virtual ICollection<RtasXEncuestaAsignada> RtasXEncuestaAsignada { get; set; }
    }
}
